[project]
name = "chameleon_robyn"
version = "0.1.2"
description = "Adds integration of the Chameleon template language to Robyn."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Michael Kennedy", email = "michael@talkpython.fm" }
]
keywords = [
    "Robyn",
    "Chameleon",
    "template",
    "templates",
    "templating",
    "template engine",
    "integration",
    "web",
    "web framework",
    "async",
    "asgi",
    "html",
    "rendering",
    "view",
    "page template",
    "tal",
    "tales",
    "metal",
    "server-side rendering",
    "ssr",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15"
]
dependencies = [
    "robyn>=0.60",
    "Chameleon"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "great-docs; python_version >= '3.11'",
]
examples = [
    "chameleon-partials",
]

[project.urls]
"Homepage" = "https://github.com/mikeckennedy/chameleon-robyn"
"Documentation" = "https://mkennedy.codes/docs/chameleon-robyn"
"Source" = "https://github.com/mikeckennedy/chameleon-robyn"
"Issues" = "https://github.com/mikeckennedy/chameleon-robyn/issues"
"PyPI" = "https://pypi.org/project/chameleon-robyn/"
"Funding" = "https://github.com/sponsors/mikeckennedy"


[build-system]
requires = ["hatchling>=1.21.0", "hatch-vcs>=0.3.0"]
build-backend = "hatchling.build"


[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.hatch.build.targets.sdist]
packages = ["chameleon_robyn"]
exclude = [
    "/.github",
    "/dist",
    "/tests",
    "/example",
    "/example-partials",
    "/venv",
    "/.venv",
    "ruff.toml",
    "requirements-dev.txt",
]

[tool.hatch.build.targets.wheel]
packages = ["chameleon_robyn"]
exclude = [
    "/.github",
    "/dist",
    "/tests",
    "/example",
    "/example-partials",
    "/venv",
    "/.venv",
    "ruff.toml",
    "requirements-dev.txt",
]
